PUS_VIEW/src/main/java/com/acl/model/Usuario.java
package com.acl.model;

import java.io.Serializable;
import java.util.List;

import com.acl.model.types.EstadoUsuarioType;

/**
 * 
 * 
 * <p>
 * Registro de versiones:
 * <ul>
 * <li>1.0 XX/YY/2016, (ACL SPA) - versión inicial
 * </ul>
 * <p>
 * 
 * 
 * <p>
 * <B>Todos los derechos reservados por ACL SPA .</B>
 */
public class Usuario implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 8109472420457810282L;
    private Long sid;
    private Integer rut;
    private String dv;
    private String nombres;
    private String apellidoPaterno;
    private String apellidoMaterno;
    private String email;
    private String fono;
    private Boolean esSuperUsuario;
    private EstadoUsuarioType estado;	
    private Contrasena contrasena = new Contrasena();
    private List<Rol> listaRoles;
    private List<Menu> listaMenu;
    private Log log;

    public Long getSid() {
	return sid;
    }

    public void setSid(Long sid) {
	this.sid = sid;
    }

    public Integer getRut() {
	return rut;
    }

    public void setRut(Integer rut) {
	this.rut = rut;
    }

    public String getDv() {
	return dv;
    }

    public void setDv(String dv) {
	this.dv = dv;
    }

    public String getNombres() {
	return nombres;
    }

    public void setNombres(String nombres) {
	this.nombres = nombres;
    }

    public String getApellidoPaterno() {
	return apellidoPaterno;
    }

    public void setApellidoPaterno(String apellidoPaterno) {
	this.apellidoPaterno = apellidoPaterno;
    }

    public String getApellidoMaterno() {
	return apellidoMaterno;
    }

    public void setApellidoMaterno(String apellidoMaterno) {
	this.apellidoMaterno = apellidoMaterno;
    }

    public String getEmail() {
	return email;
    }

    public void setEmail(String email) {
	this.email = email;
    }

    public String getFono() {
	return fono;
    }

    public void setFono(String fono) {
	this.fono = fono;
    }

    public Boolean getEsSuperUsuario() {
	return esSuperUsuario;
    }

    public void setEsSuperUsuario(Boolean esSuperUsuario) {
	this.esSuperUsuario = esSuperUsuario;
    }

    public EstadoUsuarioType getEstado() {
	return estado;
    }

    public void setEstado(EstadoUsuarioType estado) {
	this.estado = estado;
    }

    public Contrasena getContrasena() {
	return contrasena;
    }

    public void setContrasena(Contrasena contrasena) {
	this.contrasena = contrasena;
    }

    public List<Rol> getListaRoles() {
	return listaRoles;
    }

    public void setListaRoles(List<Rol> listaRoles) {
	this.listaRoles = listaRoles;
    }

    public List<Menu> getListaMenu() {
	return listaMenu;
    }

    public void setListaMenu(List<Menu> listaMenu) {
	this.listaMenu = listaMenu;
    }

    public Log getLog() {
	return log;
    }

    public void setLog(Log log) {
	this.log = log;
    }

    public String getNombreCompleto() {

	String fullName = "";
	if (this != null) {
	    if (this.nombres != null) {
		fullName = this.nombres;
	    }
	    if (this.apellidoPaterno != null) {
		fullName = fullName.concat(" ").concat(this.apellidoPaterno != null ? this.apellidoPaterno : "");
	    }
	    if (this.apellidoPaterno != null) {
		fullName = fullName.concat(" ").concat(this.apellidoMaterno != null ? this.apellidoMaterno : "");
	    }
	}

	return fullName;
    }

    @Override
    public String toString() {
	return "Usuario [sid=" + sid + ", rut=" + rut + ", dv=" + dv
		+ ", nombres=" + nombres + ", apellidoPaterno="
		+ apellidoPaterno + ", apellidoMaterno=" + apellidoMaterno
		+ ", email=" + email + ", fono=" + fono + ", esSuperUsuario="
		+ esSuperUsuario + ", estado=" + estado + ", contrasena="
		+ contrasena + ", listaRoles=" + listaRoles + ", listaMenu="
		+ listaMenu + ", log=" + log + "]";
    }

}

PUS_VIEW/src/main/webapp/resources/customcomponents/AppHeaderMenu.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:cc="http://java.sun.com/jsf/composite">

<cc:interface>
	<cc:attribute name="dummy" default="" type="java.lang.String"
		shortDescription="Dummy attribute." />
</cc:interface>
<cc:implementation>

	<h:form>
		<p:menubar>
			<p:submenu label="Mantenedores" icon="ui-icon-document">
				<p:menuitem value="Usuarios" icon="ui-icon-person"
					url="/private/mantenedores/usuario/MantenedorUsuario.jsf?faces-redirect=true" />
				<p:menuitem value="Roles" icon="ui-icon-key"
					url="/private/mantenedores/roles/MantenedorRoles.jsf?faces-redirect=true" />
				<p:menuitem value="Preguntas" icon="ui-icon-clipboard"
					url="/private/mantenedores/preguntas/MantenedorPreguntas.jsf?faces-redirect=true" />
				<p:menuitem value="Parámetros" icon="ui-icon-wrench"
					url="/private/mantenedores/parametros/MantenedorParametros.jsf?faces-redirect=true" />
				<p:menuitem value="Inicio" icon="ui-icon-home"
					url="/private/index.jsf?faces-redirect=true" />
			</p:submenu>
			<f:facet name="options">
				<h:outputText id="headerUserName"
					value="#{loginSession.usuario.nombreCompleto}"
					style="font-weight: bold;"></h:outputText>
				<p:spacer width="20px"></p:spacer>
				<p:commandButton type="button" value="Cerrar Sesión"
					icon="ui-icon-extlink" onclick="PF('cd').show();" />
			</f:facet>
		</p:menubar>

		<!--  Tooltip para visualizar informacion del usuario -->
		<p:tooltip for="headerUserName" rendered="#{loginSession.loggedIn}"
			showEffect="clip" hideEffect="explode" position="bottom">
			<p:outputLabel value="Rut: " style="font-weight: bold;" />
			<br />
			<p:outputLabel
				value="#{loginSession.usuario.rut}- #{loginSession.usuario.dv}"
				style="margin-left:10px;" />
			<br />
			<p:outputLabel value="E-mail: " style="font-weight: bold;" />
			<br />
			<p:outputLabel value="#{loginSession.usuario.email}"
				style="margin-left:10px;" />
			<br />
			<p:outputLabel value="Fono: " style="font-weight: bold;" />
			<br />
			<p:outputLabel value="#{loginSession.usuario.fono}"
				style="margin-left:10px;" />
		</p:tooltip>

		<p:confirmDialog message="¿Desea salir de la aplicación?"
			closable="false" header="Logout aplicación" severity="alert"
			widgetVar="cd">
			<p:commandButton value="Si" actionListener="#{loginSession.doLogout}"
				oncomplete="PF('cd').hide();" />
			<p:commandButton value="No" onclick="PF('cd').hide();" type="button" />
		</p:confirmDialog>

		<p:dialog widgetVar="statusDialog" modal="true" draggable="false"
			closable="false" resizable="false" showHeader="false">
			<p:graphicImage name="images/loading.gif" title="Loading" />
		</p:dialog>

		<p:ajaxStatus onstart="PF('statusDialog').show()"
			onsuccess="PF('statusDialog').hide()" />

	</h:form>
</cc:implementation>
</html>

PUS_VIEW/src/main/webapp/resources/customcomponents/SessionTimeOut.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:cc="http://java.sun.com/jsf/composite">



<cc:interface>
	<cc:attribute name="dummy" default="" type="java.lang.String"
		shortDescription="Dummy attributo"></cc:attribute>
</cc:interface>

<cc:implementation>

	<p:idleMonitor onidle="PF('sessionTimeOutDialog').show();"
		timeout="#{session.maxInactiveInterval * 1000}" />

	<p:dialog header="Sesión expirada" widgetVar="sessionTimeOutDialog"
		modal="true" closable="false" width="400" visible="false"
		resizable="false" draggable="false" fixedCenter="true">
		<h:panelGrid columns="1">
			<h:outputText value="Por motivos de seguridad su sessión ha expirado" />
			<p:commandButton style="float:right" value="cerrar sesión"
				oncomplete="PF('sessionTimeOutDialog').hide()"
				onclick="window.location='#{facesContext.externalContext.requestContextPath}/login.jsf';"></p:commandButton>

		</h:panelGrid>

	</p:dialog>

</cc:implementation>
</html>